version: 2

workflows:
  version: 2
  test-build-release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - release-pypi:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - release-github:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
jobs:
  test:
    docker:
      - image: bskaggs/ghidra
        user: root
        command: bash

    steps:
      - run:
          name: Setup git and python3 environment
          command: |
            apt-get update || apt-get update 
            apt-get install -y git python3 python3-pip
            pip3 install nose

      - checkout:
          path: /tmp/ghidra_bridge
        
      - run:
          name: Spawn ghidra bridge server and run tests
          command: |
            pip3 install jfx_bridge
            cd /tmp/ghidra_bridge
            python3 -m ghidra_bridge.install_server /tmp/ghidra_bridge/test_server
            /opt/ghidra/support/analyzeHeadless /tmp TestProject -import /bin/bash -noanalysis -scriptPath /tmp/ghidra_bridge/test_server -preScript ghidra_bridge_server.py >/tmp/script.log 2>/tmp/script.err & # Run the ghidra_bridge_server in a headless ghidra - we use non-background server, otherwise the script would exit before we could test
            ( tail -f /tmp/script.err & ) | grep -q "_bridge.bridge:serving!" # pause until we see the ghidra_bridge_server start logging messages
            python3 -c "import ghidra_bridge; b = ghidra_bridge.GhidraBridge(namespace=globals()); print(getState().getCurrentAddress())" # run a quick test for ghidra_bridge - we do this before nose, because the last nose test shuts down the bridge
            mkdir test-reports
            nosetests --with-xunit --xunit-file=/tmp/ghidra_bridge/test-reports/nosetests.xml ghidra_bridge/test_ghidra_bridge.py
            
            
      - store_test_results:
          path: /tmp/ghidra_bridge/test-reports
          
      - store_artifacts:
          path: /tmp/ghidra_bridge/test-reports
            
  build:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build ghidra_bridge package
          command: |
            pip3 install --user --upgrade setuptools # make sure we've got the latest version, to support using Markdown
            python3 setup.py sdist bdist_wheel --universal

      - store_artifacts:
          path: dist
          
      - persist_to_workspace:
          root: .
          paths:
            - dist/
  
  release-pypi:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - run:
          name: Get twine
          command: |
            pip3 install --user --upgrade twine
      - attach_workspace:
          at: ./workspace     
      - run:
          name: upload to pypi
          command: |
            python3 -m twine upload ./workspace/dist/*
            
  release-github:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run:
          name: upload to github
          command: |
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./workspace/dist/            
        
